### ISSUE TITLE
Change the default display of units (managed by pint) in live plot using ManagedDockWindow

### ISSUE THREAD

**Issue by tprssntz** [pymeasure/pymeasure#1118]
Hello,

I am experimenting with the GUI, more specifically the managed dock window for operating a new measurement setup.
One quantity I obtain is resistance. Now when I define the DATA_COLUMNS etc. I can directly provide the unit, e.g. 
```python
DATA_COLUMNS = ['resistance (ohm)']
```
When it comes to the actual live plot, the axis labels automatically obtain their labels from this definition, which results in an axis label that just reads **"Resistance (ohm)"** or when the value is small it automatically changes the label to **"Resistance (mohm)"**.
Personally, I would prefer if the units are displayed with their corresponding symbols by default, that means Ohm = $\Omega$ or temperature in °C instead of degC or so.
I tried to change the default format of the units in the units.py file, but that didn't change anything.
```python
from pymeasure.units import ureg
ureg.default_format = '~'
``` 
Any ideas where I need to change the code so I can adjust the default settings for the displayed units?

Further, I noticed that when I use °C as unit, i.e.
```python
DATA_COLUMNS = ['temperature (°C)']
```
the procedure is executed without problems and the results data also exported and stored in a file. However, the live plot doesn't show anything or update itself. The progress bar for example does it, there is just no visible live plot.
Any suggestions on how to fix this?

**Comment by BenediktBurger** [comment]
Thanks for raising the issue and bug.

If I remember correctly, it shows the text in parenthesis. So if you use the Greek letter Omega, you should get your symbol.

Why degree Celsius does not work, I don't know. 

I think you have to look in the results class, but I'm not sure.

**Comment by BenediktBurger** [comment]
I think I found the code responsible for the axis description:
https://github.com/pymeasure/pymeasure/blob/711a85ca81b746745820e8a426e0f4df39e8dcc9/pymeasure/display/widgets/plot_frame.py#L102-L116

It does not use pint at all!
Maybe pyqtgraph does not like the degree sign, I'm not sure, but some faint memory says, that there were some issues.

**Comment by CasperSchippers** [comment]
I recall seeing a similar issue earlier indeed.

I've had a quick look and think I've found this issue: a mismatch in encoding when reading or writing the file (for me, the file is written as windows-1252, but read as utf-8). Hence I propose (in PR #1123) to explcitly set the encoding to utf-8.

I've check with °C or Ω and this works fine (and are both also accepted by pint, so that didn't seem to be related.
