### ISSUE TITLE
Channel creator in a loop?

### ISSUE THREAD

**Issue by Ashwolaa** [pymeasure/pymeasure#1121]
Hi again,

I am setting up the different channels that I plan to use. 
Following the example
https://github.com/pymeasure/pymeasure/blob/master/pymeasure/instruments/lakeshore/lakeshore331.py
1) The proposed syntax goes as:
`input_A = Instrument.ChannelCreator(LakeShoreTemperatureChannel, 'A')`
`input_B = Instrument.ChannelCreator(LakeShoreTemperatureChannel, 'B')`

2) However, I would rather access the channels from a dict/list way. Thus, I tried to initialize it as:
'inputs = [Instrument.ChannelCreator(LakeShoreTemperatureChannel, f'{ch}')  for ch in ['A','B','C','D']]`

But in case 2. the variable inputs does not correctly initialize, which means the object is still of type ChannelCreator and not LakeShoreTemperatureChannel.
Is there a way to initialize it or do I have to stick to single variable?

**Comment by BenediktBurger** [comment]
Just use the first variant ("proposed syntax"), as that will create a dictionary as well: `inst.channels["A"] == inst.input_A`!

See https://pymeasure.readthedocs.io/en/latest/dev/adding_instruments/channels.html#adding-a-channel-with-channelcreator
