### ISSUE TITLE
id( ) command fails for Agilent B1500 SDA

### ISSUE THREAD

**Issue by AdMico** [pymeasure/pymeasure#1130]
Command gives:

TypeError: 'str' object is not callable

Might want to name it something other than id?

**Comment by msmttchr** [comment]
`id` is a property which returns the output of scpi command `*IDN?`, so you should not add round brackets as you would when calling a method.

**Comment by BenediktBurger** [comment]
You just use `device_ID = inst.id` to assign the ID to some variable. You use all these properties like variables of the device, not like methods.

**Comment by AdMico** [comment]
OK, then I'd say it's a documentation error, as the brackets I had just came directly from the documentation.

**Comment by msmttchr** [comment]
> OK, then I'd say it's a documentation error, as the brackets I had just came directly from the documentation.

Could you please send some reference where the documentation error is ?

**Comment by AdMico** [comment]
https://pymeasure.readthedocs.io/en/latest/api/instruments/agilent/agilentB1500.html

About halfway down the Command Translation list in General Information.

**Comment by msmttchr** [comment]
Indeed, you are right. It looks like a documentation bug. If you feel comfortable, you can open a PR for it, otherwise I will try to do it on my side. Thanks for spotting this problem.

**Comment by AdMico** [comment]
Might be better that I let you do that one (unless you can point me at a good resource for how to do it) as I haven't done that before and don't know where to start.
