### ISSUE TITLE
Race condition in test suite involving HP8116A tests

### ISSUE THREAD

**Issue by kpet** [pymeasure/pymeasure#1144]
The pass/fail outcome of the test suite is currently dependent on execution order. On my machine, I'm seeing the following failure:

```
FAILED tests/instruments/test_all_instruments.py::test_property_docstrings[HP8116A.status] - AttributeError: 'NoneType' object has no attribute 'split'
```

At first glance, this seems to indicate that the `status` property of the `HP8116A` instrument class does not have a docstring but, looking at the source code in `pymeasure/instruments/hp/hp8116a.py`, it clearly does:

```python
    @property
    def status(self):
        """Get the status byte of the 8116A as a :class:`Status` IntFlag-type enum."""
        return Status(self.adapter.connection.read_stb())
```

Upon closer inspection, it turns out that the tests for the HP8116A instrument (in `tests/instruments/hp/test_hp8116a.py`) modify the `status` property of the instrument object to mock the value of `status`:

```python
HP8116A.status = property(fget=lambda self: Status(5))
```

Depending on whether these tests run before or after the docstring test in `tests/instruments/test_all_instruments.py`, the test suite either passes or fails.

I have a plausible-looking fix for this issue that I'll propose as a PR.

**Comment by BenediktBurger** [comment]
Thanks for finding and reporting the bug.
