### ISSUE TITLE
Arbitrary serializable parameters for `Procedure`s

### ISSUE THREAD

**Issue by SengerM** [pymeasure/pymeasure#1150]
I never used PyMeasure, sorry if this is a naive question. I am going through the documentation as I am considering it for a long term project. I see it is possible to create [`Parameter`s](https://pymeasure.readthedocs.io/en/latest/api/experiment/parameters.html#) for the `Procedure`s. I see, however, that there is a limited type of parameters available, and I am surprised that there is no `str` parameter. What is the most correct way to proceed if I have to configure something using a string, e.g., target some hardware module by some arbitrary alias string? More generally, also having the possibility of passing something like a `dict` would be handy at times. How is this done?

**Comment by msmttchr** [comment]
For string, you can simply use `Parameter` class.
