### ISSUE TITLE
Sunset of classic projects

### ISSUE THREAD

**Issue by bklebel** [pymeasure/pymeasure#1152]
When checking the GitHub Project for pymeasure v1.0, I noticed the message: 

> Projects (classic) will be sunset on August 23, 2024

since this is in just a few days, it might be a good idea to do the migration, in case the contents of this project are up to date/worth saving. Since I was less involved in pymeasure recently, I am not sure about that status. 
What do you think? @bilderbuchi @BenediktBurger

**Comment by bilderbuchi** [comment]
I just created an issue milestone https://github.com/pymeasure/pymeasure/milestone/3 with all the remaining open issues on that project. The Github Project thing as we used it was weirdly parallel to (and less visible than) label milestones, so let's use that. 
I think if we want to do more fine-grained tracking, the "new" projects interface can work off of label milestones, so it seems there's no harm in doing that.

Thank you for poking us about this, it had slipped off my radar!
