### ISSUE TITLE
Allow usage of "VBS" commands for LeCroy / Teledyne oscilloscopes

### ISSUE THREAD

**Issue by RobertoRoos** [pymeasure/pymeasure#1160]
The "MAUI" class oscilloscopes mentions "VBS" commands:
![image](https://github.com/user-attachments/assets/67bfeaca-1e92-4eaf-b5c8-675318e47ea5)

(The full manual: https://cdn.teledynelecroy.com/files/manuals/maui-remote-control-and-automation-manual.pdf)

Nowhere it is explained clearly what this refers to, but I think it's [VBScript](https://en.wikipedia.org/wiki/VBScript) (Microsoft Visual Basic Scripting Edition)?

I can't find any mention of it in the docs, it would be nice to be included for the Teledyne oscilloscopes.

The Teledyne official package does support it:
```python
        print('Trying to make a connection to ', connection_string)
        dso = LeCroyDSO(ActiveDSO(connection_string))
        
        # ...

        # query the value
        response = dso.query('C1:VDIV?')
        print(response)

        # query it VBS style
        vbs_response = dso.query_vbs('app.Acquisition.C1.VerScale')
        print(vbs_response)
```
([full example](https://lecroydso.readthedocs.io/en/latest/introduction/otherexamples.html))

**Comment by BenediktBurger** [comment]
The most important question is: Can you do it with the normal serial communication or do you need another connection type?

Thanks for your idea.

Generally we are glad for better device usage.

**Comment by RobertoRoos** [comment]
I think so. I have a draft ready on my PC, I just need to borrow the company's Teledyne to test it out. If it works I'll create the PR.

**Comment by BenediktBurger** [comment]
Ok.
Thanks for improving and expanding pymeasure.
