### ISSUE TITLE
Faulty function get_buffer() in dsp7265

### ISSUE THREAD

**Issue by badarirao** [pymeasure/pymeasure#180]
I am trying to make the get_buffer()  function work, but unable to do so.
There are many issues in it like:
- self.length is not defined.
- the line "while int(self.values("M")) != 0:" should have self.values("M")[0] ?
- how is the variable count used? I don't see it changing anywhere, so how will it become greater than maxCount?
- also the command "self.values("DC. %d" % self.curve_bits[quantity])" is giving timeout error. 

Can you please check out these problems?

Thanking you,
Sincerely,
Badari

**Comment by cjermain** [comment]
@badarirao, thanks for raising this issue! The `get_buffer` method indeed has some errors as implemented. The `self.length` is indeed not defined, but appears as if it should be a property that returns the length of the buffer. I would recommend that you get the DSP7265 manual and try to manually run the commands. Once we have the working set, we can revise this method.

**Comment by badarirao** [comment]
@cjermain ,Thanks for looking into this bug.
Could you give me the algorithm on how the function is supposed to work? I am not exactly able to understand the given code.
Also, the signal recovery manual says something about implementation of serial poll in order to extract the data. I am not exactly sure on how to do this. The exact note in the manual is as follows:
" Note that when using this command with the GPIB interface the serial poll must be
used. After sending the DC command, perform repeated serial polls until bit 7 is set,
indicating that the instrument has an output waiting to be read. Then perform repeated
reads in a loop, waiting each time until bit 7 is set indicating that a new value is
available. The loop should continue until bit 1 is set, indicating that the transfer is
completed. "

Can you point me in the right direction on how to implement this?

Thanks,
Badari

**Comment by cjermain** [comment]
Unfortunately, I did not write the original function, nor do I have access to that instrument.

I would suggest determining which command provides the status, and then do a bit comparison to find the value the manual suggests. You will need to use the `DC` command to pull back the values. All of this can be done by directly calling read/write/ask on the instrument, and manually stepping through the process.

**Comment by bilderbuchi** [comment]
@badarirao did you every manage to fix the issues you report here?

**Comment by badarirao** [comment]
@bilderbuchi  No I could not fix this issue.

**Comment by bilderbuchi** [comment]
@CasperSchippers do I remember correctly that you are using such a device? If so, could you maybe take care of fixing this?

**Comment by CasperSchippers** [comment]
I have used it in the past, and I think I can get access to this system; I'll have a look

**Comment by CasperSchippers** [comment]
I started a PR (#418) to solve the issue
