### ISSUE TITLE
Polytec MSA

### ISSUE THREAD

**Issue by Endever42** [pymeasure/pymeasure#214]
Hi,

I am currently implementing a python based control class for the Polytec MSA (micro system analizer). This is tricky, since it uses some windows api functions to do this and the documentation is terrible. This also means, that you cannot connect to the device, but have to run Python locally on the machine (or in my case winpython from a USB stick). So, I am not sure if this fits the pymeasure project, but if it does, I would be happy to share this.

**Comment by Endever42** [comment]
Any comments on this? Otherwise I am thinking of creating a project for this myself, but in combination with pymeasure, the exposure would be higher.

**Comment by bilderbuchi** [comment]
@cjermain do you have an opinion about this?

**Comment by Endever42** [comment]
I would also like to add, that I had some discussion with Polytec and they would support this (only in terms of logos and awareness).

**Comment by bilderbuchi** [comment]
I'm not sure how well this fits within Pymeasure, but feel free to re-open if you disagree. :-)
