### ISSUE TITLE
Fix Sphinx warnings/errors

### ISSUE THREAD

**Issue by bilderbuchi** [pymeasure/pymeasure#294]
Our doc tests in CI emit a [number of warnings](https://travis-ci.org/github/ralph-group/pymeasure/jobs/702279699#L745-L751) that would be nice to fix.

**Comment by moritzj29** [comment]
since you adressed it yourself in 24178d739d9bbc814fa0782b4845efd0edb8b4dd, I guess this one can be closed 😄 
(just skimming through the open issues...)

**Comment by bilderbuchi** [comment]
Thanks, indeed!
