### ISSUE TITLE
Can't input float parameters in ManagedWindow if the system decimal separator is not a dot

### ISSUE THREAD

**Issue by thjungers** [pymeasure/pymeasure#310]
Hi, 

On my system, the decimal separator is set to a comma instead of a dot (this is common for non-English locales, such as French and German). With this setup, I am unable to enter float parameters in the ManagedWindow:

- when using a dot, it is ignored: 1.5 becomes 15;
- when using a comma, it is considered an invalid input: `TypeError: invalid result from ScientificInput.valueFromText(), must be real number, not NoneType`.

If I change my OS configuration to set the dot as the decimal separator, I can input float parameters correctly.

I suspect this is due to a partial localisation: Qt uses the localised decimal separator to validate the field, but in `ScientificInput.valueFromText()` the string value from the field is directly passed to ´float()´, which expects a dot in all cases.

**Comment by CasperSchippers** [comment]
Closed by #1074
