### ISSUE TITLE
Unify adapter classes

### ISSUE THREAD

**Issue by bilderbuchi** [pymeasure/pymeasure#409]
As PyVISA has become more powerful, we should 
* check if we cannot unify VISAAdapter, SerialAdapter and PrologixAdapter, or at least make the latter two just thin wrappers around the former
* check if we cannot replace the VXI11Adapter with VISAAdapter, as pyvisa apparently supports [VXI instruments](https://pyvisa.readthedocs.io/en/latest/introduction/names.html#visa-resource-syntax-and-examples), and python-vxi11 seems [essentially unmaintaineed](https://github.com/python-ivi/python-vxi11/graphs/contributors)
* Adapt the API of the TelnetAdapter to the others.
* Add tests for the various adapters

The homogenised adapter API makes instrument support easier (e.g. regarding safe/valid keywords), and leaning onto PyVISA more would probably reduce our maintenance effort.

**Comment by msmttchr** [comment]
Unfortunately Prologix is not supported by `pyvisa `and this is, I believe, the only reason why `SerialAdapter `exists.

**Comment by bilderbuchi** [comment]
* [ ] Make VISAAdapter.ask also use our own write and read instead of delegating to pyvisa.query. This makes it easier to be homogeneous across adapters, and also enables cleaner use of custom read/write methods (see TopticaAdapter). [pyvisa docs](https://pyvisa.readthedocs.io/en/latest/_modules/pyvisa/resources/messagebased.html#MessageBasedResource.query)
* [ ] roll out the use of `query_delay` across all adapters.

**Comment by bilderbuchi** [comment]
#621 adds an instrument that would also profit (i.e., eliminate duplication) from having a unified `ask` method.
