### ISSUE TITLE
Pyvisa no longer support ask, replace with query

### ISSUE THREAD

**Issue by dphaas** [pymeasure/pymeasure#432]
In resources.py
`idn = res.ask('*idn?')[:-1]`
Should be:
`idn = res.query('*idn?')[:-1]`

**Comment by LongnoseRob** [comment]
These changes seem to have been introduced with PyVisa 1.11 in Sept of 2020..

> PyVisa 1.11 also removes deprecated functions and attributes that were supposed
> to be removed  in 1.10:
> 
> - `ask`: use `query` instead
> - `ask_delay`: use `query_delay`
> - `ask_for_values`: use either `query_ascii_values` or `query_binary_values` as relevant
> - `write_values`: use either `write_ascii_values` or `write_binary_values` as relevant
> - `read_values`: use either `read_ascii_values` or `read_binary_values` as relevant
> - `query_values`: use either `query_ascii_values` or `query_binary_values` as relevant
> - `values_format`: has no equivalent simply pass the proper argument to either
>   the ascii or binary variant of the function (`read_xxxx_values`, `write_xxxx_values`,
>   `query_xxxx_values`)

https://github.com/pyvisa/pyvisa/blob/bc07e6b5b17e98eeed29cc7b196f3f4ac25e077f/CHANGES#L38

**Comment by bilderbuchi** [comment]
Well spotted, thank you! We already fixed this previously, but we have overlooked this occurrence. Are you up for [submitting a PR](https://pymeasure.readthedocs.io/en/latest/dev/contribute.html) with this small fix?

**Comment by LongnoseRob** [comment]
working on it
