### ISSUE TITLE
Thorlabs PM100 doesn't work with sensor head S130C

### ISSUE THREAD

**Issue by bleykauf** [pymeasure/pymeasure#498]
When using the Thorlabs PM100 with the measurement head S121C everything works as expected.

However, if a measurement head S130C is used instead, I get the following error message upon inialization of the ThorlabsPM100USB class:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-15-b33dbcfde9d7> in <module>
----> 1 pm = ThorlabsPM100USB('USB0::0x1313::0x8078::P0032734::INSTR')

~\Miniconda3\envs\lab\lib\site-packages\pymeasure\instruments\thorlabs\thorlabspm100usb.py in __init__(self, adapter, **kwargs)
     49             adapter, "ThorlabsPM100USB powermeter", **kwargs)
     50         self.timout = 3000
---> 51         self.sensor()
     52
     53     def measure_power(self, wavelength):

~\Miniconda3\envs\lab\lib\site-packages\pymeasure\instruments\thorlabs\thorlabspm100usb.py in sensor(self)
     82         # setting the flags; _dn are empty
     83         self.is_power, self.is_energy, _d4, _d8, \
---> 84         self.resp_settable, self.wavelength_settable, self.tau_settable, _d128, self.temperature_sens = self._flags
     85
     86     @property

ValueError: not enough values to unpack (expected 9, got 6)
```

So the problem is in this line: https://github.com/pymeasure/pymeasure/blob/658d8fb9a02bdb62f64cc3838875c0de12f49ca1/pymeasure/instruments/thorlabs/thorlabspm100usb.py#L84

I have to admit that I don't really understand what exactly is happing in this specific code block. The two different measurement heads identify as follows  ("SYST:SENSOR:IDN?"):

```
'S130C,14102240,22-Oct-2014,1,3,33\n'
```

and 

```
'S121C,18030824,08-Mrz-2018,1,18,289\n'
```

respectively.

**Comment by bilderbuchi** [comment]
> response[-1][:-1] does not invert the string,

d'oh, I was thinking of [::-1] slicing.. >.<

**Comment by bleykauf** [comment]
That's the good part: I would probably have never really thought about the
order the flags if you would not have mentioned it :)

The previous code only worked by chance, probably the worst kind of bug!

Christoph Buchner ***@***.***> schrieb am Fr., 29. Okt. 2021,
20:19:

**Comment by bilderbuchi** [comment]
> The previous code only worked by chance, probably the worst kind of bug!

Indeed...
