### ISSUE TITLE
Missing docstrings for Keithley 2306 methods

### ISSUE THREAD

**Issue by mfikes** [pymeasure/pymeasure#568]
The Keithley battery simulator instrument is missing docstrings for [`ch`](https://github.com/pymeasure/pymeasure/blob/b4d888e9ead85ef7f7af0031f2dbb44c9ce1825e/pymeasure/instruments/keithley/keithley2306.py#L665), [`relay`](https://github.com/pymeasure/pymeasure/blob/b4d888e9ead85ef7f7af0031f2dbb44c9ce1825e/pymeasure/instruments/keithley/keithley2306.py#L673), and [`pulse_current_step`](https://github.com/pymeasure/pymeasure/blob/b4d888e9ead85ef7f7af0031f2dbb44c9ce1825e/pymeasure/instruments/keithley/keithley2306.py#L542).

**Comment by bilderbuchi** [comment]
Close by #720
