### ISSUE TITLE
command_process parameter

### ISSUE THREAD

**Issue by msmttchr** [pymeasure/pymeasure#573]
During review of PR #376, some doubts were raised about the usefulness of parameter `command_process` in property creation helper methods (https://github.com/pymeasure/pymeasure/pull/376#discussion_r536805762)

The original idea of this parameter is to allow users to process command string before sending to the instrument.

I think, specific use cases needs to be identified and possibly mentioned in user documentation or make a deprecation and eventually remove this parameter

**Comment by bmoneke** [comment]
A quick check reveals, that we just use it for a deprecation warning.

I think it might have been useful for channels before we implemented `Channel`.

If we do not find any use case, I'm for deprecating this option.

**Comment by bilderbuchi** [comment]
I don't have an opinion on this, either way is fine by me.

**Comment by bmoneke** [comment]
Do you, @msmttchr or @CasperSchippers see any use specific use case?

If not, I'd deprecate the option.

**Comment by msmttchr** [comment]
Ok for me to go with deprecation.
