### ISSUE TITLE
Anaconda distribution link in quick start guide is broken

### ISSUE THREAD

**Issue by samcondon4** [pymeasure/pymeasure#589]
I can submit a PR to fix this when I have a spare minute in the next week or so. Happened to be scrolling through the `Quick start` docs and clicked the first `Anaconda distribution` link which led to a missing page.

**Comment by bilderbuchi** [comment]
Thanks, great! Sphinx has `make linkcheck` (iirc) that will visit all links in the docs and report issues. If you can it would be good to give that a pass and see what else is broken.

**Comment by samcondon4** [comment]
Great! I ran the `make linkcheck` and fixed all of the broken links in #596.

**Comment by msmttchr** [comment]
Closed through #596
