### ISSUE TITLE
Limiting number of datapoints visible on GUI & display multiple(3) curves on plot & display multiple plots in single window

### ISSUE THREAD

**Issue by Blitz-19** [pymeasure/pymeasure#626]
### Discussed in https://github.com/pymeasure/pymeasure/discussions/625

<div type='discussions-op-text'>

<sup>Originally posted by **Blitz-19** May 20, 2022</sup>
Hi,
I am new to programming and I am using ManagedWindow class to display 3 axis accelerometer data.
I am running into the following problems:
1) How can I limit my display data points to 1000 points only and then the oldest data should pop left and new data should be updated from the right side ?
I know it can be done with pyqtgraph as follows:

```
import pyqtgraph as pg
self.graph=pg.PlotWidget()
self.graph.setXRange(0, 1000, padding=0) 
```
but I am unable to access it through pymeasure.
2) Right now I can display only one axis measurement at a time although my data is made of:
data = {
                'Iteration': i,
                'acc_x': a_g[0],
                'acc_y':a_g[1],
                'acc_z':a_g[2]
                }
but I can only display only two out of these 4 values on GUI.
so my question is:
How to add 3 plots to display all 3 axes at the same time?
AND/OR
How to plot 3 curves on y-axis vs iterations on the same plot simultaneously? ( I want to try both options to see which fits better)

@CasperSchippers , @cjermain 

</div>

**Comment by bilderbuchi** [comment]
Please don't double-post - the discussion you started is the right place for the usage question :-)
