### ISSUE TITLE
0.11 release preparation

### ISSUE THREAD

**Issue by bilderbuchi** [pymeasure/pymeasure#730]
After having already merged #660, I would like to wait to
* [x] ~~integrate #718~~ (postponed) 
* [x] integrate #712 

and then cut the next release, 0.11. I think we have a good number of new big features, and it would be good to get feedback on those.

Any other feature issues/PRs you would like to **urgently** see included in the next release? Mind that every additional one will delay the release further. 
Instrument additions will be reviewed continuously (and go out with the release that happens next), but unfortunately that takes a lot of time and effort.

**Comment by bmoneke** [comment]
The PRs you mentioned, together with #660 and the protocol tests, are a great improvement, which should be published.

Instruments are not urgent, in my opinion, as those who need an instrument may always copy the instrument file and are ready to go.

**Comment by CasperSchippers** [comment]
I think that that when the PRs mentioned by @bilderbuchi are merged 0.11 is good to go.

**Comment by bilderbuchi** [comment]
OK then, let's do it like this, thanks for the feedback!

**Comment by bmoneke** [comment]
@bilderbuchi suggested to move #718 to another release, in order to have more time to nail down the final implementation (changing the instruments might change the channel implementation).

As we already have enough good content to deploy and both #503 and #701 are merged, I'm for releasing now (without #718).

What do you think @CasperSchippers , @msmttchr ?

**Comment by msmttchr** [comment]
Ok for me.

**Comment by CasperSchippers** [comment]
Fine with me

**Comment by bilderbuchi** [comment]
> I'll branch off a separate branch so that the PR review/merging work can continue unhindered.

I'll use `develop` as that will get CI testing without creating a PR to master (which could hinder PR merges). The tag will then maybe happen on that branch (if we have merged the channel PR to master in the meantime), and merged into master immediately afterwards.

**Comment by bilderbuchi** [comment]
It's done, v0.11.0 tagged and released on pypi and conda-forge! :partying_face: 
Thank you everyone for your contributions!

**Comment by msmttchr** [comment]
Congratulations 👏👏👏

Il Sab 19 Nov 2022, 14:42 Christoph Buchner ***@***.***> ha
scritto:

**Comment by CasperSchippers** [comment]
Nice, thanks, Good job!!

**Comment by LongnoseRob** [comment]
_Very nice_, thank you!

**Comment by bmoneke** [comment]
Thank you!

**Comment by LongnoseRob** [comment]
Github shows me still V0.10 as latest release..
![Screenshot_2022-11-19_23-19-51](https://user-images.githubusercontent.com/17066917/202855448-72a0552c-26f9-4e8f-8ebb-f9bd1e14b54e.png)

**Comment by bilderbuchi** [comment]
Thanks! I don't know exactly what the deal is with "Releases" vs. Git tags, but I manually did this now.

**Comment by LongnoseRob** [comment]
> Thanks! I don't know exactly what the deal is with "Releases" vs. Git tags (annoying), but I manually did this now.

No worries, now it shows v0.11  correctly
