### ISSUE TITLE
Telnetlib deprecated

### ISSUE THREAD

**Issue by Max-Herbold** [pymeasure/pymeasure#744]
Python is dropping support for telnetlib in 3.11 and will be removed in 3.13. 

Mentioned by #567, the whole adapter could just be removed because VISA can handle it.

**Comment by bmoneke** [comment]
Duplicate of #668 
If you know, how to do the replacement or want to figure it out, I invite you to do it. I have not worked with it and was not confident enough to make the change without having a possibility to test it.
We can do it together, if you want.
