### ISSUE TITLE
ChannelCreator does not work in parent class

### ISSUE THREAD

**Issue by bmoneke** [pymeasure/pymeasure#759]
In #758, the ChannelCreator did not work, unless used in the last class defined, because the class dict contains only the items defined in that class, not inherited.

Does "inspect" help here?

**Comment by msmttchr** [comment]
Indeed. This was overlooked. I think inspect doesn't help and you need to use a strategy based on MRO (see `_setup_special_names`) as an example.

**Comment by bmoneke** [comment]
I had a test (and might still have), which tests inheritance, but not (yet) in this constellation.

It was good to delay the channels for 0.12.

**Comment by msmttchr** [comment]
Correction: inspect should work as well.

**Comment by bilderbuchi** [comment]
> class dict contains only the items defined in that class, not inherited.

does `dir(ChildClass)` not work? This should also contain inherited attributes afaik.

**Comment by msmttchr** [comment]
`dir `give you the list of attribute names(including inherited ones), but it doesn't return the value.
