### ISSUE TITLE
files without copyright notice

### ISSUE THREAD

**Issue by LongnoseRob** [pymeasure/pymeasure#817]
While browsing the source tree, I realized there are several files without a copyright notice:
Could be seen as a follow-up to #812

- [`instruments/keithley/keithley2260B.py`](../tree/master/pymeasure/instruments/keithley/keithley2260B.py)
- [`instruments/keysight/__init__.py`](../tree/master/pymeasure/instruments/keysight/__init__.py)
- [`instruments/texio/texioPSW360L30.py`](../tree/master/pymeasure/instruments/texio/texioPSW360L30.py)
- [`tests/experiment/data/__init__.py`](../tree/master/pymeasure/tests/experiment/data/__init__.py) 

Q1: is the `__init_.py ` actually required  in `tests/experiment/data`?  it is a 0 byte file
Q2: Should the example files also get a copyright-notice?

**Comment by bmoneke** [comment]
Thanks for finding these files.

An init file (even without content) in a folder marks that folder as a (sub)package and serves therefore a purpose. I'm unsure, whether that empty file should get a copryright notice.

Example files should get such a notice, as they are part of pymeasure, I'd say.

**Comment by LongnoseRob** [comment]
> Thanks for finding these files.
> 
> An init file (even without content) in a folder marks that folder as a (sub)package and serves therefore a purpose. I'm unsure, whether that empty file should get a copryright notice.

Thanks for the explanation.
I am also unsure if we should include a copyright notice until there is actually content in the file..

 
> Example files should get such a notice, as they are part of pymeasure, I'd say.

I am with you here also, lets wait for some more replies/comments

**Comment by msmttchr** [comment]
I agree with your opinion on the copyright notice applicability (both cases)
