### ISSUE TITLE
Python 3.8 incompatibility

### ISSUE THREAD

**Issue by msmttchr** [pymeasure/pymeasure#910]
I have just found that the line below gives an error with python 3.8.
https://github.com/pymeasure/pymeasure/blob/ead6fe5033872a0e9243c2f270ea95b6fe2fded4/pymeasure/display/widgets/plot_frame.py#L73

Possibly this dictionary 'oring' has been introduced in a subsequent version of python (3.9 is OK for example).

**Comment by mcdo0486** [comment]
Yup, I can confirm that. I ran into that line with a user's anaconda pymeasure install. Should have filed an issue then.
