### ISSUE TITLE
Improve CI

### ISSUE THREAD

**Issue by bmoneke** [pymeasure/pymeasure#946]
Based on the experience of adding CI to pyleco (https://github.com/pymeasure/pyleco/pull/7), I'd like to back port some ideas to pymeasure.

- Mamba resulted in a faster setup build time, so it should be used, I think.
- we could introduce test coverage for the instruments and adapters, or at least for the core elements, that is adapters and core instrument classes like Instrument, Channel, CommonBase.

**Comment by bilderbuchi** [comment]
Good ideas! Duplicate of/better tracked in #348?

**Comment by bmoneke** [comment]
Duplicate of #348 (sorry, working on the phone...)
