### ISSUE TITLE
Actions (CI run?) badge is broken

### ISSUE THREAD

**Issue by bmoneke** [pymeasure/pymeasure#974]
The CI run badge on the documentation is broken (on readthedocs and in the documetns viewer for the `index.rst` file.

https://github.com/pymeasure/pymeasure/blob/78db2c9175bf0535c8f391a4ba7b1ad2883f40c1/docs/index.rst?plain=1#L19

**Comment by bilderbuchi** [comment]
Fixed by [f1898bf](https://github.com/pymeasure/pymeasure/commit/f1898bfe1d6d950870672f8d980a86852545386d) ( I directly pushed that)

**Comment by bmoneke** [comment]
It's broken in `index.rst` (original issue cause) as well.

**Comment by bilderbuchi** [comment]
oops, I missed that.

**Comment by CasperSchippers** [comment]
I also took the liberty to directly fix this on master (only just realised that you might just have pushed it direclty to master in order to get it in before the 0.13.1, but oh well :sweat_smile:)
