### ISSUE TITLE
failing to install editable mode when following instructions "Contributing" 

### ISSUE THREAD

**Issue by bernhardlang** [pymeasure/pymeasure#980]
The issue is already discussed in #893. I suggest to add a line in the documentation "Contributing", just before section "Working on a new feature" which gives the hint to update pip in case the command "pip install -e ." fails with an error saying "ERROR: File "setup.py" not found."

**Comment by bmoneke** [comment]
Hello @bernhardlang 

Would you mind to do it and to open a pull request?

As a minimal work, you might go to the file, click on the "edit button" (the pen) and change the file with the "commit" button.
That will create a fork and branch, if necessary, and open a  PR.
