### ISSUE TITLE
How to use properties when no specific termination character is set in the protocol

### ISSUE THREAD

**Issue by seb5g** [pymeasure/pymeasure#997]
I have a very old but working instrument. It communicate over serial but the command list is quite weird and sometime there is a termination character, sometime there isn't. Sometimes there is an answer after writing sometimes not.

Therefore my question is how to handle that? at the moment I always have a timeouterror when setting something because the read immediately returns a timeout error (when no response is expected or when there is no termination character).

Is it possible to change the termination character dynamically within the get/set process? 

My workaround is to write a method to do a write then I would actually use the timeout error raised during reading as a termination character. But for this to work I have to make sure to read bytes one by one until there is a timeout, then I will return the string.

Thanks for the pointers (if there are...)
Seb

**Comment by BenediktBurger** [comment]
The place to write your logic in is the "read" method.
There you can read bytes (one ore more) if you wish. The method is called "read_bytes". Actually, that method can read until timeout. 
There you could set the termination char before doing the read etc.

I have also one instrument, which gets hiccups (zero byte) from time to time and the normal read method doesn't like non ASCII chars. Therefore I read byte for byte and return the correct ones in the "read" method.

**Comment by seb5g** [comment]
Of course subclassify the read method...silly me
